swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: 10.217.151.64:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - https
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /postItinerary:
    x-swagger-router-controller: chat-it
    post:
      description: Post itinerary form data
      # used as the method name of the controller
      operationId: postItinerary
      parameters:
        - name: data
          in: body
          description: Post itinerary form data, postItinerary.data is an array of days, with each day containing an array of hours of that day. Within each array of hours there is a JSON object containing what the user did. Ex. location, activity, time of activity, duration of activity.  
          schema:
            $ref: "#/definitions/postItinerary"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
         
  /login:
    x-swagger-router-controller: chat-it
    post:
      description: Post login
      # used as the method name of the controller
      operationId: postLogin
      parameters:
        - name: username
          in: query
          description: username to fetch
          required: true
          type: string
        - name: password
          in: query
          description: password
          required: true
          type: string
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
                  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  entry:
    required:
      - location
      - activity
      - time
      - duration
    properties:
      location:
        type: string
      activity: 
        type: string
      time:
        type: string
      duration:
        type: integer
        
  postItinerary:
    required:
      - location
      - dateFrom
      - dateTo
      - data
    properties:
      location:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
      data:
        type: array
        items: 
          type: array
          items: 
            $ref: "#/definitions/entry"
          

        