swagger: "2.0"
info:
  version: "0.0.1"
  title: Chatlt
# during dev, should point to your local machine
host: 10.217.151.64:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - https
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
            
  /postItinerary:
    x-swagger-router-controller: chat-it
    post:
      description: Post itinerary form data
      # used as the method name of the controller
      operationId: postItinerary
      parameters:
        - name: data
          in: body
          description: Post itinerary form data, postItinerary.data is an array of days, with each day containing an array of hours of that day. Within each array of hours there is a JSON object containing what the user did. Ex. location, activity, time of activity, duration of activity.  
          schema:
            $ref: "#/definitions/postItinerary"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
         
  /login:
    x-swagger-router-controller: chat-it
    post:
      description: Post login
      # used as the method name of the controller
      operationId: postLogin
      parameters:
        - name: username
          in: query
          description: username to fetch
          required: true
          type: string
        - name: password
          in: query
          description: password
          required: true
          type: string
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
 
  /register:
    x-swagger-router-controller: chat-it
    post:
      description: new user registration
      # used as the method name of the controller
      operationId: postRegister
      parameters:
        - name: username
          in: query
          description: new username
          required: true
          type: string
        - name: email
          in: query
          description: users email
          required: true
          type: string
        - name: password
          in: query
          description: password of the new user
          required: true
          type: string
          
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            

  /review:
    x-swagger-router-controller: chat-it
    post:
      description: user posting review for the itinerary 
      # used as the method name of the controller
      operationId: Post Review
      parameters:
        - name: itineraryID
          in: query
          description: ID of the itinerary to fetch
          required: false
          type: string
        - name: title
          in: query
          description: title of the comment
          required: true
          type: string
        - name: data
          in: body
          description: review
          schema:
            $ref: "#/definitions/postReview"
        
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
          
            
                  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  entry:
    required:
      - location
      - activity
      - time
      - duration
    properties:
      location:
        type: string
      activity: 
        type: string
      time:
        type: string
      duration:
        type: integer
        
  postItinerary:
    required:
      - location
      - dateFrom
      - dateTo
      - data
    properties:
      location:
        type: string
      dateFrom:
        type: string
      dateTo:
        type: string
      data:
        type: array
        items: 
          type: array
          items: 
            $ref: "#/definitions/entry"
    
  postReview:
    required:
      - data
    properties:
      data:
        type: string
        items:
           $ref: "#/definitions/postReview"
            
          

        